### ISSUE TITLE
Unraid installation

### ISSUE THREAD

**Issue by cbackas** [domainzero/bookstack-dark-theme#13]
I'm trying to get this theme going on unRaid but in the docker container's appdata folder I can't find any public folders or anything. Theres no indication of any HTML that is actually being loaded and shown to me.... It all seems to be inside the instance of the docker's VM or something (/var/www/...) and I can't change that... Are there workarounds for that or am I screwed to use the default theme here?

**Comment by domainzero** [comment]
Theoretically you could just put `<link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/domainzero/bookstack-dark-theme/master/dark-theme.css">` in the Bookstack settings > custom HTML head content and have the git version of this stylesheet load.

Give that a shot and let me know if it works.

Keep in mind that at the time of this writing the stylesheet is undergoing some changes due to the new Bookstack redesign so some stuff might be a little wonky looking and it may not be any fault of your own 😜

**Comment by cbackas** [comment]
Hmm adding that didn't change anything either... But its alright I'm not even 100% sold on bookstack as my wiki software yet

**Comment by domainzero** [comment]
You might want to double check your browser console too and see if it's complaining about cross origin resource sharing.

Another option is to take everything inside the stylesheet and put it in a `<style>` tag in the Custom HTML Head Content area too.

**Comment by mattkerrison** [comment]
`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://raw.githubusercontent.com/domainzero/bookstack-dark-theme/master/dark-theme.css with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.`


Yep CORS is complaining, shame, I'm using the docker image as well, being able to add a hosted css file through the settings page would be really handy, love the look of the dark theme from the screenshots.

**Comment by domainzero** [comment]
have you tried a `docker copy` to move the file inside the container serving bookstack?
