### ISSUE TITLE
PDF Export Unreadable

### ISSUE THREAD

**Issue by wh1337** [domainzero/bookstack-dark-theme#7]
First off, love the theme. 

When you export to PDF, the export is unreadable. Do you know if there is a way to change that to pull it the default theme in for exports?

**Comment by domainzero** [comment]
Hey @wdhodges, sorry for the long delay.

Are you using the built-in PDF exporter or `wkhtmltopdf`?
My PDFs work normally. Let me check to see if I've changed anything on my install.

**Comment by wh1337** [comment]
Hey no worries! I was using the built in exporter, I can choco install `wkhtmltopdf`

**Comment by domainzero** [comment]
I'm using the built-in exporter too.
I'll keep digging to see if I've changed anything.

FWIW I'm on Linux, on BookStack v0.24.3.

**Comment by domainzero** [comment]
Ha, this is a weird one.
I have my stylesheet publicly exposed. I am calling it in the CUSTOM HTML CONTENT via `<link rel='stylesheet' href="//<my-domain</bonus.css">`. My PDF exports normally with the default export stylesheet because it can't load my stylesheet for some reason.

If I instead call it via `<link rel='stylesheet' href="https://<my-domain>/bonus.css">` the PDF export is largely unreadable as it is loading my CSS instead of the default sheet.

Anyway, that's just a workaround. The real solution should be setting the `background-color` that the PDF renderer uses so the PDF actually renders properly.

**Comment by domainzero** [comment]
Alright, sorry to spam you with live updates here, but I found a few solutions.

1. Use the `@page` selector to set the font color to something darker. This comes the problem of having dark text on a dark background in the case of block quotes, code, etc.

2. Set the `body { background-color:}` value to `#282a36`, which renders the entire background of the PDF the same color as the live site. This comes with the problem of having white margins that kinda muck up the whole aesthetic.  You can remove the margins by setting them to `0px` via the `@page` selector, but that could mess up the document if you actually wanted to print it.

3. The third option is to use the "workaround" detailed above, i.e. using an indefinite path and letting the browser choose how to load the CSS, as it appears DOMPDF can't load the CSS if you use just `//` versus `http://` or `https://` and will default to its own CSS. This is the option I would use if you actually wanted to print a PDF you created in BookStack.

I think I'm going to push a change that favors the 2nd option.
